# Generated by Django 4.1.13 on 2024-09-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(choices=[('Sheet1', 'Sheet1'), ('Sheet2', 'Sheet2'), ('Sheet3', 'Sheet3'), ('Sheet4', 'Sheet4'), ('Sheet5', 'Sheet5')], max_length=50)),
                ('symbol', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('signal', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
