# Generated by Django 4.1.13 on 2024-09-22 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_datasheet_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
